### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute 'node'

### ISSUE THREAD

**Issue by orestis-z** [mcasl/PipeGraph#5]
Traceback (most recent call last):
  File "scripts/train_regressor.py", line 199, in <module>
    main(args)
  File "scripts/train_regressor.py", line 106, in main
    model.fit(features_train, scores_train)
  File "/Users/orestis/.local/share/virtualenvs/-HnoKq6z_/lib/python3.7/site-packages/pipegraph/base.py", line 184, in fit
    self._fit_graph = build_graph(self.fit_connections)
  File "/Users/orestis/.local/share/virtualenvs/-HnoKq6z_/lib/python3.7/site-packages/pipegraph/base.py", line 497, in build_graph
    current_node = graph.node[name]
AttributeError: 'DiGraph' object has no attribute 'node'

**Comment by mcasl** [comment]
If you share the code you were running may be I can help you solve the issue.
